version: 2

before:
  hooks:
    - go mod download

builds:
  - id: lsm
    main: ./cmd/lsm
    binary: lsm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - ppc64le
      - s390x
    goarm:
      - "6"
      - "7"

brews:
  - name: lsm
    homepage: https://github.com/semihtok/lsm
    commit_author:
      name: semihtok
      email: ibrahim@semihtok.com
    caveats: ""
    description: "lsm (ls-modern) high-performance, concurrent file system analysis tool that efficiently calculates and displays detailed directory and file sizes, optimized for handling large directories and complex file structures."
    license: Apache-2.0
    dependencies:
      - name: git
      - name: go

checksum:
  name_template: "checksums.txt"
  algorithm: sha256