before:
  hooks:
    - go mod download
builds:
  - id: lsm
    main: ./cmd/lsm
    binary: lsm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - ppc64le
      - s390x
    goarm: [6, 7]

brews:
  - # GitHub/GitLab repository to push the formula to
    tap:
      owner: semihtok
      name: lsm

    name: lsm
    homepage: https://github.com/semihtok/lsm

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: semihtok
      email: ibrahim@semihtok.com

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: ""

    # Your app's description.
    # Default is empty.
    description: "lsm (ls-modern) high-performance, concurrent file system analysis tool that efficiently calculates and 
    displays detailed directory and file sizes, optimized for handling large directories and complex file structures."

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache 2.0"

    # Packages your package depends on.
    dependencies:
      - name: git
      - name: go
checksum:
  name_template: "checksums.txt"
  algorithm: sha256